version: "3.2"
services:
  php:
    build: "./php/"
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: "./apache/"
    depends_on:
      - php
      - mysql
    networks:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend: